# Generated by Django 5.2.8 on 2025-11-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buspass',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AddField(
            model_name='buspass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='capacity',
            field=models.PositiveIntegerField(default=40, help_text='Total seat capacity of the bus/route'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buspass',
            name='pass_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique pass number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='buspass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_passes', to='transport.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='bus_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.busroute'),
        ),
    ]
